import type { SupportedLanguage } from "@/types/profile.types";

const TEAM_MATCHES_KO = {
  tabTitle: "경기",
  listTitle: "경기 일정",
  createTitle: "경기 등록",
  detailTitle: "경기 상세",
  tournamentTitle: "대진표",
  previousMonth: "이전 달",
  nextMonth: "다음 달",
  addMatch: "경기 등록",
  opponentTbd: "상대 미정",
  venueFallback: "정해진 구장이 없어요",
  typeFriendly: "친선",
  typeLeague: "리그",
  typeTournament: "대회",
  statusScheduled: "예정",
  statusOngoing: "진행중",
  statusFinished: "완료",
  statusCancelled: "취소",
  statusDisputed: "이의 제기",
  statusFinalized: "최종 확정",
  statusAwaitingConfirmation: "확정 대기",
  statusAwaitingResult: "결과 대기",
  statusAutoFinalized: "자동 확정",
  noMatchesForDate: "이 날은 경기가 없어요.",
  noMatchesInMonth: "이번 달에는 등록된 경기가 없어요.",
  selectDateHint: "날짜를 선택하면 해당 일정만 볼 수 있어요.",
  backToMatches: "경기 목록으로",
  attendanceTitle: "출석 투표",
  attendanceYes: "참석",
  attendanceNo: "불참",
  attendanceMaybe: "미정",
  attendancePending: "미응답",
  attendanceSummary: "출석 현황",
  participantsTitle: "참석자 목록",
  opponentLabel: "상대팀",
  opponentSearch: "팀 검색",
  opponentSearchPlaceholder: "팀 이름으로 검색",
  opponentSearchEmpty: "검색 결과가 없어요.",
  opponentUnknownToggle: "상대 미정",
  dateLabel: "날짜",
  timeLabel: "시간",
  venueLabel: "장소",
  matchTypeLabel: "경기 유형",
  sportLabel: "종목",
  submitCreate: "경기 등록",
  createLoading: "경기를 등록하는 중입니다.",
  validationMatchType: "경기 유형을 선택해주세요.",
  validationDate: "날짜를 선택해주세요.",
  validationTime: "시간을 선택해주세요.",
  validationOpponent: "상대팀을 선택하거나 상대 미정을 체크해주세요.",
  validationFuture: "과거 시간으로는 등록할 수 없어요.",
  today: "오늘",
  tomorrow: "내일",
  ddayPrefix: "D-",
  thisTeam: "우리 팀",
  openCreate: "새 경기 만들기",
  votesYes: "참석",
  votesNo: "불참",
  votesMaybe: "미정",
  saveVoteError: "출석 응답을 저장하지 못했어요.",
  noAttendancePoll: "출석 투표가 아직 준비되지 않았어요.",
  noMembers: "표시할 팀 멤버가 없어요.",
  detailMetaDivider: " · ",
  leagueSoonBadge: "준비 중",
  tournamentNameLabel: "대회명",
  tournamentNamePlaceholder: "대회명을 입력해주세요",
  tournamentTeamsTitle: "참가팀 등록",
  tournamentTeamsHint: "내 팀을 포함해 최대 4팀까지 등록할 수 있어요.",
  tournamentBracketHint: "4팀이 등록되면 랜덤 대진표가 자동 생성됩니다.",
  tournamentCreateSuccess: "대회가 생성되었어요.",
  tournamentCreateLoading: "대회를 생성하는 중입니다.",
  tournamentValidationName: "대회명을 입력해주세요.",
  tournamentValidationTeams: "참가팀은 최소 2팀, 최대 4팀까지 등록할 수 있어요.",
  tournamentTeamsCount: "참가팀",
  removeTeam: "제거",
  noTournamentTeams: "아직 등록된 참가팀이 없어요.",
  bracketSemifinal: "준결승",
  bracketFinal: "결승",
  bracketTbd: "TBD",
  tournamentStatusOpen: "모집중",
  tournamentStatusInProgress: "진행중",
  tournamentStatusFinished: "종료",
  scorePending: "경기 전",
  attendanceLegendYes: "참석",
  attendanceLegendNo: "불참",
  attendanceLegendMaybe: "미정",
  noDateFilter: "이번 달 전체",
  calendarWeekSun: "일",
  calendarWeekMon: "월",
  calendarWeekTue: "화",
  calendarWeekWed: "수",
  calendarWeekThu: "목",
  calendarWeekFri: "금",
  calendarWeekSat: "토",
  tournamentAddTeam: "팀 추가",
  tournamentSelectTeam: "팀 선택",
  tournamentHostBadge: "개최팀",
  tournamentMaxTeams: "최대 4팀",
  awayUnknownLabel: "상대 미정",
} as const;

const TEAM_MATCHES_EN = {
  tabTitle: "Matches",
  listTitle: "Match calendar",
  createTitle: "Create match",
  detailTitle: "Match detail",
  tournamentTitle: "Tournament bracket",
  previousMonth: "Previous month",
  nextMonth: "Next month",
  addMatch: "Create match",
  opponentTbd: "Opponent TBD",
  venueFallback: "Venue TBD",
  typeFriendly: "Friendly",
  typeLeague: "League",
  typeTournament: "Tournament",
  statusScheduled: "Scheduled",
  statusOngoing: "Ongoing",
  statusFinished: "Finished",
  statusCancelled: "Cancelled",
  statusDisputed: "Disputed",
  statusFinalized: "Finalized",
  statusAwaitingConfirmation: "Awaiting confirmation",
  statusAwaitingResult: "Awaiting result",
  statusAutoFinalized: "Auto finalized",
  noMatchesForDate: "No matches on this day.",
  noMatchesInMonth: "There are no matches scheduled this month.",
  selectDateHint: "Select a date to filter the match list.",
  backToMatches: "Back to matches",
  attendanceTitle: "Attendance vote",
  attendanceYes: "Attend",
  attendanceNo: "Absent",
  attendanceMaybe: "Maybe",
  attendancePending: "Pending",
  attendanceSummary: "Attendance summary",
  participantsTitle: "Attendance list",
  opponentLabel: "Opponent",
  opponentSearch: "Search teams",
  opponentSearchPlaceholder: "Search by team name",
  opponentSearchEmpty: "No teams found.",
  opponentUnknownToggle: "Opponent TBD",
  dateLabel: "Date",
  timeLabel: "Time",
  venueLabel: "Venue",
  matchTypeLabel: "Match type",
  sportLabel: "Sport",
  submitCreate: "Create match",
  createLoading: "Creating match...",
  validationMatchType: "Select a match type.",
  validationDate: "Select a date.",
  validationTime: "Select a time.",
  validationOpponent: "Select an opponent or mark it as TBD.",
  validationFuture: "Scheduled time must be in the future.",
  today: "Today",
  tomorrow: "Tomorrow",
  ddayPrefix: "D-",
  thisTeam: "Our team",
  openCreate: "New match",
  votesYes: "Attend",
  votesNo: "Absent",
  votesMaybe: "Maybe",
  saveVoteError: "Could not save the attendance response.",
  noAttendancePoll: "Attendance poll is not ready yet.",
  noMembers: "There are no members to display.",
  detailMetaDivider: " · ",
  leagueSoonBadge: "Soon",
  tournamentNameLabel: "Tournament name",
  tournamentNamePlaceholder: "Enter tournament name",
  tournamentTeamsTitle: "Tournament teams",
  tournamentTeamsHint: "Include your team and add up to four teams total.",
  tournamentBracketHint: "A random bracket is created automatically once four teams are registered.",
  tournamentCreateSuccess: "Tournament created successfully.",
  tournamentCreateLoading: "Creating tournament...",
  tournamentValidationName: "Enter a tournament name.",
  tournamentValidationTeams: "Register between 2 and 4 teams.",
  tournamentTeamsCount: "Teams",
  removeTeam: "Remove",
  noTournamentTeams: "No teams registered yet.",
  bracketSemifinal: "Semifinal",
  bracketFinal: "Final",
  bracketTbd: "TBD",
  tournamentStatusOpen: "Open",
  tournamentStatusInProgress: "In progress",
  tournamentStatusFinished: "Finished",
  scorePending: "Not started",
  attendanceLegendYes: "Attend",
  attendanceLegendNo: "Absent",
  attendanceLegendMaybe: "Maybe",
  noDateFilter: "All this month",
  calendarWeekSun: "Sun",
  calendarWeekMon: "Mon",
  calendarWeekTue: "Tue",
  calendarWeekWed: "Wed",
  calendarWeekThu: "Thu",
  calendarWeekFri: "Fri",
  calendarWeekSat: "Sat",
  tournamentAddTeam: "Add team",
  tournamentSelectTeam: "Select team",
  tournamentHostBadge: "Host",
  tournamentMaxTeams: "Up to 4 teams",
  awayUnknownLabel: "Opponent TBD",
} as const;

const TEAM_MATCHES_VI = {
  tabTitle: "Tran dau",
  listTitle: "Lich thi dau",
  createTitle: "Tao tran dau",
  detailTitle: "Chi tiet tran dau",
  tournamentTitle: "So do giai dau",
  previousMonth: "Thang truoc",
  nextMonth: "Thang sau",
  addMatch: "Tao tran dau",
  opponentTbd: "Chua co doi thu",
  venueFallback: "Chua co san thi dau",
  typeFriendly: "Giao huu",
  typeLeague: "Giai dau",
  typeTournament: "Tournament",
  statusScheduled: "Sap dien ra",
  statusOngoing: "Dang dien ra",
  statusFinished: "Da xong",
  statusCancelled: "Da huy",
  statusDisputed: "Dang tranh chap",
  statusFinalized: "Da chot",
  statusAwaitingConfirmation: "Cho xac nhan",
  statusAwaitingResult: "Cho ket qua",
  statusAutoFinalized: "Tu dong chot",
  noMatchesForDate: "Khong co tran dau trong ngay nay.",
  noMatchesInMonth: "Khong co tran dau nao trong thang nay.",
  selectDateHint: "Chon ngay de loc lich thi dau.",
  backToMatches: "Quay lai lich dau",
  attendanceTitle: "Diem danh",
  attendanceYes: "Co mat",
  attendanceNo: "Vang",
  attendanceMaybe: "Co the",
  attendancePending: "Chua tra loi",
  attendanceSummary: "Tong hop diem danh",
  participantsTitle: "Danh sach diem danh",
  opponentLabel: "Doi thu",
  opponentSearch: "Tim doi",
  opponentSearchPlaceholder: "Tim theo ten doi",
  opponentSearchEmpty: "Khong tim thay doi nao.",
  opponentUnknownToggle: "Chua co doi thu",
  dateLabel: "Ngay",
  timeLabel: "Gio",
  venueLabel: "San",
  matchTypeLabel: "Loai tran",
  sportLabel: "Mon",
  submitCreate: "Tao tran dau",
  createLoading: "Dang tao tran dau...",
  validationMatchType: "Hay chon loai tran.",
  validationDate: "Hay chon ngay.",
  validationTime: "Hay chon gio.",
  validationOpponent: "Hay chon doi thu hoac danh dau chua co doi thu.",
  validationFuture: "Thoi gian phai nam trong tuong lai.",
  today: "Hom nay",
  tomorrow: "Ngay mai",
  ddayPrefix: "D-",
  thisTeam: "Doi cua toi",
  openCreate: "Them tran dau",
  votesYes: "Co mat",
  votesNo: "Vang",
  votesMaybe: "Co the",
  saveVoteError: "Khong the luu phan hoi diem danh.",
  noAttendancePoll: "Chua co thong tin diem danh.",
  noMembers: "Khong co thanh vien de hien thi.",
  detailMetaDivider: " · ",
  leagueSoonBadge: "Sap co",
  tournamentNameLabel: "Ten giai dau",
  tournamentNamePlaceholder: "Nhap ten giai dau",
  tournamentTeamsTitle: "Dang ky doi",
  tournamentTeamsHint: "Bao gom doi cua ban va toi da 4 doi.",
  tournamentBracketHint: "Khi du 4 doi, he thong se tao so do ngau nhien.",
  tournamentCreateSuccess: "Da tao giai dau.",
  tournamentCreateLoading: "Dang tao giai dau...",
  tournamentValidationName: "Hay nhap ten giai dau.",
  tournamentValidationTeams: "Hay dang ky tu 2 den 4 doi.",
  tournamentTeamsCount: "So doi",
  removeTeam: "Xoa",
  noTournamentTeams: "Chua co doi nao dang ky.",
  bracketSemifinal: "Ban ket",
  bracketFinal: "Chung ket",
  bracketTbd: "TBD",
  tournamentStatusOpen: "Mo",
  tournamentStatusInProgress: "Dang dien ra",
  tournamentStatusFinished: "Da ket thuc",
  scorePending: "Chua da",
  attendanceLegendYes: "Co mat",
  attendanceLegendNo: "Vang",
  attendanceLegendMaybe: "Co the",
  noDateFilter: "Ca thang nay",
  calendarWeekSun: "CN",
  calendarWeekMon: "T2",
  calendarWeekTue: "T3",
  calendarWeekWed: "T4",
  calendarWeekThu: "T5",
  calendarWeekFri: "T6",
  calendarWeekSat: "T7",
  tournamentAddTeam: "Them doi",
  tournamentSelectTeam: "Chon doi",
  tournamentHostBadge: "Chu nha",
  tournamentMaxTeams: "Toi da 4 doi",
  awayUnknownLabel: "Chua co doi thu",
} as const;

export type TeamMatchesCopy = {
  [K in keyof typeof TEAM_MATCHES_EN]: string;
};

const COPY: Record<SupportedLanguage, TeamMatchesCopy> = {
  ko: TEAM_MATCHES_KO,
  vi: TEAM_MATCHES_VI,
  en: TEAM_MATCHES_EN,
};

export function getTeamMatchesCopy(language: SupportedLanguage): TeamMatchesCopy {
  return COPY[language] ?? COPY.en;
}