export type RegionOption = {
  label: string;
  value: string;
};

export type VietnamProvinceGroup = {
  label: string;
  value: string;
  districts: RegionOption[];
};

export const VIETNAM_REGION_GROUPS: VietnamProvinceGroup[] = [
  {
    label: "Ho Chi Minh City",
    value: "HCM",
    districts: [
      { label: "District 1", value: "HCM-D1" },
      { label: "District 2", value: "HCM-D2" },
      { label: "District 3", value: "HCM-D3" },
      { label: "District 4", value: "HCM-D4" },
      { label: "District 5", value: "HCM-D5" },
      { label: "District 6", value: "HCM-D6" },
      { label: "District 7", value: "HCM-D7" },
      { label: "District 8", value: "HCM-D8" },
      { label: "District 9", value: "HCM-D9" },
      { label: "District 10", value: "HCM-D10" },
      { label: "District 11", value: "HCM-D11" },
      { label: "District 12", value: "HCM-D12" },
      { label: "Binh Thanh", value: "HCM-BTH" },
      { label: "Binh Tan", value: "HCM-BTN" },
      { label: "Go Vap", value: "HCM-GV" },
      { label: "Phu Nhuan", value: "HCM-PN" },
      { label: "Tan Binh", value: "HCM-TB" },
      { label: "Tan Phu", value: "HCM-TP" },
      { label: "Thu Duc City", value: "HCM-TD" },
      { label: "Binh Chanh", value: "HCM-BC" },
      { label: "Cu Chi", value: "HCM-CC" },
      { label: "Hoc Mon", value: "HCM-HM" },
      { label: "Nha Be", value: "HCM-NB" },
      { label: "Can Gio", value: "HCM-CG" },
    ],
  },
  {
    label: "Hanoi",
    value: "HAN",
    districts: [
      { label: "Ba Dinh", value: "HAN-BD" },
      { label: "Hoan Kiem", value: "HAN-HK" },
      { label: "Hai Ba Trung", value: "HAN-HBT" },
      { label: "Dong Da", value: "HAN-DD" },
      { label: "Tay Ho", value: "HAN-TH" },
      { label: "Cau Giay", value: "HAN-CG" },
      { label: "Thanh Xuan", value: "HAN-TX" },
      { label: "Hoang Mai", value: "HAN-HM" },
      { label: "Long Bien", value: "HAN-LB" },
      { label: "Ha Dong", value: "HAN-HD" },
      { label: "Nam Tu Liem", value: "HAN-NTL" },
      { label: "Bac Tu Liem", value: "HAN-BTL" },
      { label: "Son Tay", value: "HAN-ST" },
      { label: "Ba Vi", value: "HAN-BV" },
      { label: "Chuong My", value: "HAN-CM" },
      { label: "Dan Phuong", value: "HAN-DP" },
      { label: "Dong Anh", value: "HAN-DA" },
      { label: "Gia Lam", value: "HAN-GL" },
      { label: "Hoai Duc", value: "HAN-HDU" },
      { label: "Me Linh", value: "HAN-ML" },
      { label: "My Duc", value: "HAN-MD" },
      { label: "Phu Xuyen", value: "HAN-PX" },
      { label: "Phuc Tho", value: "HAN-PT" },
      { label: "Quoc Oai", value: "HAN-QO" },
      { label: "Soc Son", value: "HAN-SS" },
      { label: "Thanh Oai", value: "HAN-TO" },
      { label: "Thanh Tri", value: "HAN-TT" },
      { label: "Thach That", value: "HAN-TT2" },
      { label: "Thuong Tin", value: "HAN-TTI" },
      { label: "Ung Hoa", value: "HAN-UH" },
    ],
  },
  {
    label: "Da Nang",
    value: "DAD",
    districts: [
      { label: "Hai Chau", value: "DAD-HC" },
      { label: "Thanh Khe", value: "DAD-TK" },
      { label: "Son Tra", value: "DAD-ST" },
      { label: "Ngu Hanh Son", value: "DAD-NHS" },
      { label: "Cam Le", value: "DAD-CL" },
      { label: "Lien Chieu", value: "DAD-LC" },
      { label: "Hoa Vang", value: "DAD-HV" },
      { label: "Hoang Sa", value: "DAD-HS" },
    ],
  },
  {
    label: "Hue",
    value: "HUE",
    districts: [
      { label: "Phu Xuan", value: "HUE-PX" },
      { label: "Thuan Hoa", value: "HUE-TH" },
      { label: "Huong Tra", value: "HUE-HT" },
      { label: "Huong Thuy", value: "HUE-HY" },
      { label: "Phong Dien", value: "HUE-PD" },
      { label: "Quang Dien", value: "HUE-QD" },
      { label: "Phu Vang", value: "HUE-PV" },
      { label: "Phu Loc", value: "HUE-PL" },
      { label: "A Luoi", value: "HUE-AL" },
      { label: "Nam Dong", value: "HUE-ND" },
    ],
  },
  {
    label: "Hai Phong",
    value: "HPH",
    districts: [
      { label: "Hong Bang", value: "HPH-HB" },
      { label: "Ngo Quyen", value: "HPH-NQ" },
      { label: "Le Chan", value: "HPH-LC" },
      { label: "Kien An", value: "HPH-KA" },
      { label: "Hai An", value: "HPH-HA" },
      { label: "Duong Kinh", value: "HPH-DK" },
      { label: "Do Son", value: "HPH-DS" },
      { label: "An Duong", value: "HPH-AD" },
      { label: "An Lao", value: "HPH-AL" },
      { label: "Kien Thuy", value: "HPH-KT" },
      { label: "Thuy Nguyen", value: "HPH-TN" },
      { label: "Tien Lang", value: "HPH-TL" },
      { label: "Vinh Bao", value: "HPH-VB" },
      { label: "Cat Hai", value: "HPH-CH" },
      { label: "Bach Long Vi", value: "HPH-BLV" },
    ],
  },
  {
    label: "Can Tho",
    value: "CTO",
    districts: [
      { label: "Ninh Kieu", value: "CTO-NK" },
      { label: "Binh Thuy", value: "CTO-BT" },
      { label: "Cai Rang", value: "CTO-CR" },
      { label: "O Mon", value: "CTO-OM" },
      { label: "Thot Not", value: "CTO-TN" },
      { label: "Phong Dien", value: "CTO-PD" },
      { label: "Thoi Lai", value: "CTO-TL" },
      { label: "Co Do", value: "CTO-CD" },
      { label: "Vinh Thanh", value: "CTO-VT" },
    ],
  },
  {
    label: "Binh Duong",
    value: "BDU",
    districts: [
      { label: "Thu Dau Mot", value: "BDU-TDM" },
      { label: "Di An", value: "BDU-DAN" },
      { label: "Thuan An", value: "BDU-TA" },
      { label: "Tan Uyen", value: "BDU-TU" },
      { label: "Ben Cat", value: "BDU-BC" },
      { label: "Bau Bang", value: "BDU-BB" },
      { label: "Phu Giao", value: "BDU-PG" },
      { label: "Dau Tieng", value: "BDU-DT" },
      { label: "Bac Tan Uyen", value: "BDU-BTU" },
    ],
  },
  {
    label: "Dong Nai",
    value: "DNA",
    districts: [
      { label: "Bien Hoa", value: "DNA-BH" },
      { label: "Long Khanh", value: "DNA-LK" },
      { label: "Long Thanh", value: "DNA-LT" },
      { label: "Nhon Trach", value: "DNA-NT" },
      { label: "Trang Bom", value: "DNA-TB" },
      { label: "Vinh Cuu", value: "DNA-VC" },
      { label: "Cam My", value: "DNA-CM" },
      { label: "Dinh Quan", value: "DNA-DQ" },
      { label: "Tan Phu", value: "DNA-TP" },
      { label: "Thong Nhat", value: "DNA-TN" },
      { label: "Xuan Loc", value: "DNA-XL" },
    ],
  },
  {
    label: "Ba Ria - Vung Tau",
    value: "BRV",
    districts: [
      { label: "Vung Tau", value: "BRV-VT" },
      { label: "Ba Ria", value: "BRV-BR" },
      { label: "Phu My", value: "BRV-PM" },
      { label: "Long Dien", value: "BRV-LD" },
      { label: "Dat Do", value: "BRV-DD" },
      { label: "Xuyen Moc", value: "BRV-XM" },
      { label: "Chau Duc", value: "BRV-CD" },
      { label: "Con Dao", value: "BRV-CDO" },
    ],
  },
  {
    label: "Khanh Hoa",
    value: "KHH",
    districts: [
      { label: "Nha Trang", value: "KHH-NT" },
      { label: "Cam Ranh", value: "KHH-CR" },
      { label: "Ninh Hoa", value: "KHH-NH" },
      { label: "Van Ninh", value: "KHH-VN" },
      { label: "Dien Khanh", value: "KHH-DK" },
      { label: "Cam Lam", value: "KHH-CL" },
      { label: "Khanh Vinh", value: "KHH-KV" },
      { label: "Khanh Son", value: "KHH-KS" },
      { label: "Truong Sa", value: "KHH-TS" },
    ],
  },
  {
    label: "Lam Dong",
    value: "LDO",
    districts: [
      { label: "Da Lat", value: "LDO-DL" },
      { label: "Bao Loc", value: "LDO-BL" },
      { label: "Bao Lam", value: "LDO-BLM" },
      { label: "Cat Tien", value: "LDO-CT" },
      { label: "Da Huoai", value: "LDO-DH" },
      { label: "Da Teh", value: "LDO-DT2" },
      { label: "Di Linh", value: "LDO-DIL" },
      { label: "Don Duong", value: "LDO-DD" },
      { label: "Duc Trong", value: "LDO-DT" },
      { label: "Lam Ha", value: "LDO-LH" },
      { label: "Lac Duong", value: "LDO-LD" },
    ],
  },
  {
    label: "Dak Lak",
    value: "DLK",
    districts: [
      { label: "Buon Ma Thuot", value: "DLK-BMT" },
      { label: "Buon Don", value: "DLK-BD" },
      { label: "Cu Kuin", value: "DLK-CK" },
      { label: "Cu M'gar", value: "DLK-CMG" },
      { label: "Ea H'leo", value: "DLK-EH" },
      { label: "Ea Kar", value: "DLK-EK" },
      { label: "Krong Ana", value: "DLK-KA" },
      { label: "Krong Bong", value: "DLK-KBO" },
      { label: "Krong Buk", value: "DLK-KB" },
      { label: "Krong Nang", value: "DLK-KN" },
      { label: "Krong Pac", value: "DLK-KP" },
      { label: "Lak", value: "DLK-LAK" },
      { label: "M'Drak", value: "DLK-MD" },
    ],
  },
  {
    label: "Quang Ninh",
    value: "QNI",
    districts: [
      { label: "Ha Long", value: "QNI-HL" },
      { label: "Cam Pha", value: "QNI-CP" },
      { label: "Mong Cai", value: "QNI-MC" },
      { label: "Uong Bi", value: "QNI-UB" },
      { label: "Dong Trieu", value: "QNI-DT" },
      { label: "Quang Yen", value: "QNI-QY" },
      { label: "Van Don", value: "QNI-VD" },
      { label: "Co To", value: "QNI-CT" },
      { label: "Ba Che", value: "QNI-BC" },
      { label: "Binh Lieu", value: "QNI-BL" },
      { label: "Dam Ha", value: "QNI-DH" },
      { label: "Hai Ha", value: "QNI-HH" },
      { label: "Tien Yen", value: "QNI-TY" },
    ],
  },
  {
    label: "Bac Ninh",
    value: "BNH",
    districts: [
      { label: "Bac Ninh City", value: "BNH-BNC" },
      { label: "Tu Son", value: "BNH-TS" },
      { label: "Gia Binh", value: "BNH-GB" },
      { label: "Luong Tai", value: "BNH-LT" },
      { label: "Que Vo", value: "BNH-QV" },
      { label: "Thuan Thanh", value: "BNH-TT" },
      { label: "Tien Du", value: "BNH-TD" },
      { label: "Yen Phong", value: "BNH-YP" },
    ],
  },
  {
    label: "Hai Duong",
    value: "HDU",
    districts: [
      { label: "Hai Duong City", value: "HDU-HDC" },
      { label: "Chi Linh", value: "HDU-CL" },
      { label: "Binh Giang", value: "HDU-BG" },
      { label: "Cam Giang", value: "HDU-CG" },
      { label: "Gia Loc", value: "HDU-GL" },
      { label: "Kim Thanh", value: "HDU-KT" },
      { label: "Kinh Mon", value: "HDU-KM" },
      { label: "Nam Sach", value: "HDU-NS" },
      { label: "Ninh Giang", value: "HDU-NG" },
      { label: "Thanh Ha", value: "HDU-TH" },
      { label: "Thanh Mien", value: "HDU-TM" },
      { label: "Tu Ky", value: "HDU-TK" },
    ],
  },
  {
    label: "Quang Nam",
    value: "QNA",
    districts: [
      { label: "Hoi An", value: "QNA-HA" },
      { label: "Tam Ky", value: "QNA-TK" },
      { label: "Dien Ban", value: "QNA-DB" },
      { label: "Dai Loc", value: "QNA-DL" },
      { label: "Duy Xuyen", value: "QNA-DX" },
      { label: "Hiep Duc", value: "QNA-HD" },
      { label: "Nam Giang", value: "QNA-NG" },
      { label: "Nam Tra My", value: "QNA-NTM" },
      { label: "Nui Thanh", value: "QNA-NT" },
      { label: "Phu Ninh", value: "QNA-PN" },
      { label: "Phuoc Son", value: "QNA-PS" },
      { label: "Que Son", value: "QNA-QS" },
      { label: "Thang Binh", value: "QNA-TB" },
      { label: "Tien Phuoc", value: "QNA-TP" },
    ],
  },
  {
    label: "Binh Dinh",
    value: "BDI",
    districts: [
      { label: "Quy Nhon", value: "BDI-QN" },
      { label: "An Nhon", value: "BDI-AN" },
      { label: "An Lao", value: "BDI-AL" },
      { label: "Hoai An", value: "BDI-HA" },
      { label: "Hoai Nhon", value: "BDI-HN" },
      { label: "Phu Cat", value: "BDI-PC" },
      { label: "Phu My", value: "BDI-PM" },
      { label: "Tay Son", value: "BDI-TS" },
      { label: "Tuy Phuoc", value: "BDI-TP" },
      { label: "Van Canh", value: "BDI-VC" },
      { label: "Vinh Thanh", value: "BDI-VT" },
    ],
  },
  {
    label: "Phu Yen",
    value: "PYE",
    districts: [
      { label: "Tuy Hoa", value: "PYE-TH" },
      { label: "Dong Hoa", value: "PYE-DH" },
      { label: "Song Cau", value: "PYE-SC" },
      { label: "Dong Xuan", value: "PYE-DX" },
      { label: "Phu Hoa", value: "PYE-PH" },
      { label: "Son Hoa", value: "PYE-SH" },
      { label: "Song Hinh", value: "PYE-SHI" },
      { label: "Tay Hoa", value: "PYE-TH2" },
      { label: "Tuy An", value: "PYE-TA" },
    ],
  },
  {
    label: "Long An",
    value: "LAN",
    districts: [
      { label: "Tan An", value: "LAN-TA" },
      { label: "Kien Tuong", value: "LAN-KT" },
      { label: "Ben Luc", value: "LAN-BL" },
      { label: "Can Duoc", value: "LAN-CD" },
      { label: "Can Giuoc", value: "LAN-CG" },
      { label: "Chau Thanh", value: "LAN-CT" },
      { label: "Duc Hoa", value: "LAN-DH" },
      { label: "Duc Hue", value: "LAN-DH2" },
      { label: "Moc Hoa", value: "LAN-MH" },
      { label: "Tan Hung", value: "LAN-THU" },
      { label: "Tan Thanh", value: "LAN-TTH" },
      { label: "Tan Tru", value: "LAN-TTR" },
      { label: "Thanh Hoa", value: "LAN-TH" },
      { label: "Thu Thua", value: "LAN-TTU" },
      { label: "Vinh Hung", value: "LAN-VH" },
    ],
  },
  {
    label: "An Giang",
    value: "AGI",
    districts: [
      { label: "Long Xuyen", value: "AGI-LX" },
      { label: "Chau Doc", value: "AGI-CD" },
      { label: "Tan Chau", value: "AGI-TC" },
      { label: "An Phu", value: "AGI-AP" },
      { label: "Chau Phu", value: "AGI-CP" },
      { label: "Chau Thanh", value: "AGI-CT" },
      { label: "Cho Moi", value: "AGI-CM" },
      { label: "Phu Tan", value: "AGI-PT" },
      { label: "Thoai Son", value: "AGI-TS" },
      { label: "Tinh Bien", value: "AGI-TB" },
      { label: "Tri Ton", value: "AGI-TT" },
    ],
  },
  {
    label: "Kien Giang",
    value: "KGG",
    districts: [
      { label: "Rach Gia", value: "KGG-RG" },
      { label: "Ha Tien", value: "KGG-HT" },
      { label: "Phu Quoc", value: "KGG-PQ" },
      { label: "An Bien", value: "KGG-AB" },
      { label: "An Minh", value: "KGG-AM" },
      { label: "Chau Thanh", value: "KGG-CT" },
      { label: "Giong Rieng", value: "KGG-GR" },
      { label: "Go Quao", value: "KGG-GQ" },
      { label: "Hon Dat", value: "KGG-HD" },
      { label: "Kien Hai", value: "KGG-KH" },
      { label: "Kien Luong", value: "KGG-KL" },
      { label: "Tan Hiep", value: "KGG-TH" },
      { label: "U Minh Thuong", value: "KGG-UMT" },
      { label: "Vinh Thuan", value: "KGG-VT" },
    ],
  },
  {
    label: "Dong Thap",
    value: "DTP",
    districts: [
      { label: "Cao Lanh", value: "DTP-CL" },
      { label: "Sa Dec", value: "DTP-SD" },
      { label: "Hong Ngu City", value: "DTP-HNC" },
      { label: "Cao Lanh District", value: "DTP-CLD" },
      { label: "Chau Thanh", value: "DTP-CT" },
      { label: "Hong Ngu District", value: "DTP-HN" },
      { label: "Lai Vung", value: "DTP-LV" },
      { label: "Lap Vo", value: "DTP-LV2" },
      { label: "Tam Nong", value: "DTP-TN" },
      { label: "Tan Hong", value: "DTP-TH" },
      { label: "Thanh Binh", value: "DTP-TB" },
      { label: "Thap Muoi", value: "DTP-TM" },
    ],
  },
  {
    label: "Ben Tre",
    value: "BTE",
    districts: [
      { label: "Ben Tre City", value: "BTE-BTC" },
      { label: "Ba Tri", value: "BTE-BT" },
      { label: "Binh Dai", value: "BTE-BD" },
      { label: "Chau Thanh", value: "BTE-CT" },
      { label: "Cho Lach", value: "BTE-CL" },
      { label: "Giong Trom", value: "BTE-GT" },
      { label: "Mo Cay Bac", value: "BTE-MCB" },
      { label: "Mo Cay Nam", value: "BTE-MCN" },
      { label: "Thanh Phu", value: "BTE-TP" },
    ],
  },
  {
    label: "Soc Trang",
    value: "SOC",
    districts: [
      { label: "Soc Trang City", value: "SOC-STC" },
      { label: "Chau Thanh", value: "SOC-CT" },
      { label: "Cu Lao Dung", value: "SOC-CLD" },
      { label: "Ke Sach", value: "SOC-KS" },
      { label: "Long Phu", value: "SOC-LP" },
      { label: "My Tu", value: "SOC-MT" },
      { label: "My Xuyen", value: "SOC-MX" },
      { label: "Nga Nam", value: "SOC-NN" },
      { label: "Thanh Tri", value: "SOC-TTR" },
      { label: "Tran De", value: "SOC-TD" },
      { label: "Vinh Chau", value: "SOC-VC" },
    ],
  },
  {
    label: "Vinh Long",
    value: "VLG",
    districts: [
      { label: "Vinh Long City", value: "VLG-VLC" },
      { label: "Binh Minh", value: "VLG-BM" },
      { label: "Binh Tan", value: "VLG-BT" },
      { label: "Long Ho", value: "VLG-LH" },
      { label: "Mang Thit", value: "VLG-MT" },
      { label: "Tam Binh", value: "VLG-TB" },
      { label: "Tra On", value: "VLG-TO" },
      { label: "Vung Liem", value: "VLG-VL" },
    ],
  },
  {
    label: "Tra Vinh",
    value: "TVI",
    districts: [
      { label: "Tra Vinh City", value: "TVI-TVC" },
      { label: "Cang Long", value: "TVI-CL" },
      { label: "Cau Ke", value: "TVI-CK" },
      { label: "Cau Ngang", value: "TVI-CN" },
      { label: "Chau Thanh", value: "TVI-CT" },
      { label: "Duyen Hai", value: "TVI-DH" },
      { label: "Duyen Hai Town", value: "TVI-DHT" },
      { label: "Tieu Can", value: "TVI-TC" },
      { label: "Tra Cu", value: "TVI-TCU" },
    ],
  },
  {
    label: "Ca Mau",
    value: "CAA",
    districts: [
      { label: "Ca Mau City", value: "CAA-CMC" },
      { label: "Cai Nuoc", value: "CAA-CN" },
      { label: "Dam Doi", value: "CAA-DD" },
      { label: "Nam Can", value: "CAA-NC" },
      { label: "Ngoc Hien", value: "CAA-NH" },
      { label: "Phu Tan", value: "CAA-PT" },
      { label: "Thoi Binh", value: "CAA-TB" },
      { label: "Tran Van Thoi", value: "CAA-TVT" },
      { label: "U Minh", value: "CAA-UM" },
    ],
  },
];

const PROVINCE_OPTIONS: RegionOption[] = VIETNAM_REGION_GROUPS.map(({ label, value }) => ({
  label,
  value,
}));

const DISTRICT_OPTIONS_BY_PROVINCE = Object.fromEntries(
  VIETNAM_REGION_GROUPS.map((province) => [province.value, province.districts])
) as Record<string, RegionOption[]>;

export function getVietnamProvinceOptions(): RegionOption[] {
  return PROVINCE_OPTIONS;
}

export function getVietnamDistrictOptions(provinceCode: string | null): RegionOption[] {
  if (!provinceCode) {
    return [];
  }

  return DISTRICT_OPTIONS_BY_PROVINCE[provinceCode] ?? [];
}

export function isValidVietnamProvinceCode(provinceCode: string): boolean {
  return Boolean(DISTRICT_OPTIONS_BY_PROVINCE[provinceCode]);
}

export function isValidVietnamDistrictCode(provinceCode: string, districtCode: string): boolean {
  return getVietnamDistrictOptions(provinceCode).some((district) => district.value === districtCode);
}
